name: Dotnet Actions Demo

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: restore dependencies
        run: dotnet restore
        
      - name: build and print
        run: |
          echo application building
          dotnet build --no-restore
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: restore dependencies
        run: dotnet restore
        
      - name: test
        run: dotnet test --no-restore
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: dhiraj2001/testapp:latest
