name: Dotnet Actions Demo

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: restore dependencies
        run: dotnet restore
        
      - name: build and print
        run: |
          echo application building
          dotnet build --no-restore
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: restore dependencies
        run: dotnet restore
        
      - name: test
        run: dotnet test --no-restore
  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: dhiraj2001/testapp
        tags: latest
        registry: docker.io
        dockerfile: CalculatorApp/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
