name: Dotnet Actions Demo

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: restore dependencies
        run: dotnet restore
        
      - name: build and print
        run: |
          echo application building
          dotnet build --no-restore
